# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 14:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('password', models.CharField(max_length=40)),
                ('head_portrait', models.CharField(max_length=260)),
                ('username', models.CharField(default=False, max_length=20)),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=1)),
                ('school', models.CharField(default=False, max_length=50)),
                ('address', models.CharField(default=False, max_length=100)),
                ('hometown', models.CharField(default=False, max_length=70)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
